### ISSUE TITLE
Some libraries missing from wasm ghc-pkg

### ISSUE THREAD

**Issue by dfordivam** [WebGHC/wasm-cross#19]
Specifically `random`
This library is built along with ghc, but I think not getting registered in ghc-pkg. This might be a nixpkgs issue.

These are registered.
```
    Cabal-2.3.0.0
    array-0.5.2.0
    base-4.12.0.0
    binary-0.8.5.1
    bytestring-0.10.8.2
    containers-0.5.11.0
    deepseq-1.4.4.0
    directory-1.3.2.3
    filepath-1.4.2
    ghc-boot-8.5
    ghc-boot-th-8.5
    ghc-compact-0.1.0.0
    ghc-prim-0.5.2.0
    ghci-8.5
    haskeline-0.7.4.2
    hpc-0.6.0.3
    integer-simple-0.1.1.1
    mtl-2.2.2
    parsec-3.1.13.0.0.0.0.0
    pretty-1.1.3.6
    process-1.6.3.0
    rts-1.0
    stm-2.4.5.0
    template-haskell-2.14.0.0
    text-1.2.3.0
    time-1.8.0.2
    transformers-0.5.5.0
    unix-2.8.0.0
```

**Comment by ElvishJerricco** [comment]
I don't think `random` is shipped with GHC, is it? It's not in `ghc-pkg list` with GHC installed via Nix or Stack.

**Comment by dfordivam** [comment]
It is shipped with ghc, moreover the ghc test-suite uses it...

If it is not in normal ghc-pkg installation also, then I am not sure what to do..

**Comment by ElvishJerricco** [comment]
How do you conclude that it's shipped with GHC if it does not show up in the default package db shipped with GHC?

**Comment by dfordivam** [comment]
Oh I mean it is in the `ghc/libraries` folder

**Comment by ElvishJerricco** [comment]
@dfordivam ah. I'm guessing that's for the bootstrapping phase where it builds `ghc-cabal`. I don't think it's actually a core library that ships with GHC.

**Comment by dtzWill** [comment]
> I don't think random is shipped with GHC, is it? It's not in ghc-pkg list with GHC installed via Nix or Stack.

Bouncing through recent GHC commits and saw this, which perhaps explains a bit?
https://github.com/ghc/ghc/commit/0905fec089b3270f540c7ee33959cbf8ecfcb4d7

**Comment by dfordivam** [comment]
Right, so nothing to do here then...
