### ISSUE TITLE
Cannot build libraries via nix generic-builder

### ISSUE THREAD

**Issue by dfordivam** [WebGHC/wasm-cross#20]
While building libraries using nix, it errors out during linking due to https://github.com/WebGHC/ghc/issues/7

I think it is due to `-staticlib` flag.

This flag might be redundant as the libraries built via `cabal` (without -staticlib) seem to work fine.

**Comment by ElvishJerricco** [comment]
Hm. I don't see `-staticlib` being passed anywhere in `generic-builder`. Is this a `generic-builder` thing or a `Cabal` thing?

**Comment by dfordivam** [comment]
I think is the one causing this. 

generic-builder.nix
```
# --enable-static does not work on windows. This is a bug in GHC.
# --enable-static will pass -staticlib to ghc, which only works for mach-o and elf.
assert hostPlatform.isWindows -> enableStaticLibraries == false;
```

**Comment by ElvishJerricco** [comment]
That's just an assertion. It can't change what actually happens in the build.

**Comment by ElvishJerricco** [comment]
Oh but I see what you mean now. We need to make sure we're not passing `--enable-static` to cabal
