### ISSUE TITLE
Raspberry Pi support for GHC.

### ISSUE THREAD

**Issue by ElvishJerricco** [WebGHC/wasm-cross#9]
`nixpkgsRpi` currently works for C programs. But `libffi` expects to find `__aeabi_unwind_cpp_pr0` from `glibc`, which is not present in `musl`. It *may* be present in `libunwind`, but that would require #1 to at least be partially fixed.

**Comment by ElvishJerricco** [comment]
http://sushihangover.github.io/llvm-and-the-arm-elf-arm-dot-exidx-star-section/

**Comment by dfordivam** [comment]
This is outside the scope of `WebGHC` work, so closing this.
